[tools]
direnv     = '2.28.0'
github-cli = "latest"
ripgrep = "latest"
zoxide = "latest"
fzf = "0.53"
neovim = "0.9"
tmux = "latest"
poetry = "latest"
nodejs     = '16.5.0'
yarn = "latest"
starship = "latest"
git = "latest"
python = "latest"
node = "lts"
go = "latest"
difftastic = "0.49"

[env]

[settings]
experimental = true
