[tools]
direnv = "latest"
github-cli = "latest"
ripgrep = "latest"
zoxide = "latest"
fzf = "latest"
neovim = "0.9"
tmux = "latest"
poetry = "latest"
nodejs     = '16.5.0'
yarn = "latest"
starship = "latest"
git = "latest"
python = "latest"
node = "lts"
go = "latest"
difftastic = "0.49"
rust = "latest"
pipx = "latest"

[env]

[settings]
experimental = true
